### ISSUE TITLE
Translucent Glass

### ISSUE THREAD

**Issue by misner5** [GPSnoopy/RayTracingInVulkan#11]
Hey I have another question about experimenting with the material library you've made.  It's such an awesome library I was hoping you had some advice on how to extend it to new materials.  What I was trying to do was create a semi-opaque glass...

Sort of a mix of ScatterLambertian & ScatterDieletric in Scatter.glsl

I tried a bunch of different approaches to doing this but they all ended up looking really plastic and bad.  The closest I came to it working was using RandomFloat to generate a value and blending between 2 RayPayloads like this:

```
float rSeed = RandomFloat(seed);
if( rSeed > .5){
	const bool isScattered = dot(direction, normal) < 0;
	const vec4 colorAndDistance = vec4(m.Diffuse.rgb * texColor.rgb, t);
	const vec4 scatter = vec4(normal + RandomInUnitSphere(seed), isScattered ? 1 : 0);
	return RayPayload(colorAndDistance, scatter, seed);
}
else{
	return RayPayload(vec4(texColor.rgb, t), vec4(reflect(direction, normal), 1), seed);
}
```

Do you have any ideas on how this could be done better?
Anyways thanks again for this great project.

**Comment by GPSnoopy** [comment]
I have to admit this probably goes outside my zone of comfort. If you are trying to get more accurate materials, or just explore other possible equations, my first reflex would be to go and read http://www.pbr-book.org/ (main website at https://www.pbrt.org/, see the gallery at https://www.pbrt.org/gallery.html for examples).

I've heard the PBR book is one of the main reference in modern ray tracing and material equations.

**Comment by misner5** [comment]
Ok cheers... thanks for sharing those links.
The glass looks so awesome in the project you've made it seemed good to try and extend the current material library as a base.
I'll study these references, thanks for being so helpful.

**Comment by GPSnoopy** [comment]
I cannot take credit for that, it's all from Peter Shirley's books: https://raytracing.github.io/

That's what I like about them. They're easy to understand, but give quite good results.
