### ISSUE TITLE
VK_KHR_ray_tracing on RTX2080

### ISSUE THREAD

**Issue by freeman40** [GPSnoopy/RayTracingInVulkan#13]
Thanks for your very cool port of Peter Shirley's ray tracing demo.  I have learnt a lot from it.

Should the VK_KHR_ray_tracing branch work on an Nvidia GeForce RTX2080 card?
When I run it I get: FATAL: missing required extensions: VK_KHR_deferred_host_operations, VK_KHR_pipeline_library, VK_KHR_ray_tracing.

Clearly the missing extensions are the reason it isn't working.  What I don't understand is why those extensions are missing.
I have the latest Nvidia graphics driver (451.48), and the latest Vulkan SDK (1.2.141.2).
Do I need to install something else to get those extensions (I would have thought the graphics driver is enough), or is it simply that VK_KHR_ray_tracing is not supported on the RTX2080?  (but that seems a bit odd.  It *is* a ray tracing card after all)

**Comment by GPSnoopy** [comment]
Hi @freeman40,

The VK_KHR_ray_tracing extension specifications have not yet been finalized and are still considered beta. So for the moment you have to use developer drivers from NVIDIA: https://developer.nvidia.com/vulkan-driver.

Be aware that I don't always have those installed myself, as some games do misbehave (YMMV). Once the specs are finalized and/or the proper drivers are mainstream, I intend on merging the VK_KHR_ray_tracing branch onto master. Patiently waiting...

BTW I like your https://github.com/freeman40/VulkanApps repository. :-)

**Comment by freeman40** [comment]
Thanks :-)
Installing the beta drivers (currently 443.41) did indeed do the trick (it also appears necessary to tick the "perform a clean install" box during the installation process).

Thanks also for the commit about "shader binding table alignment" - that saved me a bit of work figuring out what the validation layers were complaining about when I updated to SDK 1.2.141.2.
