### ISSUE TITLE
[question] how would you approach motion blur?

### ISSUE THREAD

**Issue by zhuker** [GPSnoopy/RayTracingInVulkan#17]
according to nvidia vulkan doesnt support ray tracing motion blur
https://developer.nvidia.com/blog/how-to-get-started-with-optix-7/

have you thought about implementing it still?

**Comment by GPSnoopy** [comment]
Apparently Ampere added hardware support for ray tracing motion blur:
https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/ampere/pdf/NVIDIA-ampere-GA102-GPU-Architecture-Whitepaper-V1.pdf

I suspect this will be expose somehow by a Vulkan extension? Without it, VK_NV_ray_tracing requires you to explicitly come up with a lot of nasty work around. I guess you'd have to extend the AABB of a given object to match its `[t0, t1]` domain and write a custom intersection shader to chose a particular random ray that matches the a particular `t` time in the model local reference frame.

**Comment by GPSnoopy** [comment]
You're not the only one wondering about this:
https://twitter.com/syoyo/status/1307755584628822017
