### ISSUE TITLE
Corrupted screen on Radeon 6000 series

### ISSUE THREAD

**Issue by GPSnoopy** [GPSnoopy/RayTracingInVulkan#24]
From @VoidPtr74

![rt_6900xt_1](https://user-images.githubusercontent.com/10282472/106357636-33ca2380-62ff-11eb-9f4b-61c5b3b6a5b7.jpg)
![rt_6900xt_2](https://user-images.githubusercontent.com/10282472/106357637-3462ba00-62ff-11eb-9601-48e4791502f5.jpg)
![rt_6900xt_3](https://user-images.githubusercontent.com/10282472/106357638-3462ba00-62ff-11eb-870d-99e69ccdddfa.jpg)
![rt_6900xt_4](https://user-images.githubusercontent.com/10282472/106357639-3462ba00-62ff-11eb-8a32-d3fe7177e5f7.jpg)
![rt_6900xt_5](https://user-images.githubusercontent.com/10282472/106358589-18faad80-6305-11eb-980f-5a4c0521f86f.jpg)

**Comment by GPSnoopy** [comment]
Committed https://github.com/GPSnoopy/RayTracingInVulkan/commit/902cd38a33544c8e53cd96bb5f9a22606b83758a to fix image count = 1.

**Comment by GPSnoopy** [comment]
Committed https://github.com/GPSnoopy/RayTracingInVulkan/commit/97dfaca5ecdfcd0f6b857c2d943fe9479c1b5509 to fix the alignment validation errors.

**Comment by GPSnoopy** [comment]
@VoidPtr74 confirmed that commenting out the `UserInterface` calls solves the rendering problem. This also might explain Issue #19.

**Comment by GPSnoopy** [comment]
Upgraded to latest ImGui Vulkan backends, but didn't solve the issue (https://github.com/GPSnoopy/RayTracingInVulkan/commit/fab9002ca12dca9cd24e41bc3ce1307bfad588be).

**Comment by GPSnoopy** [comment]
Potential fix on https://github.com/GPSnoopy/RayTracingInVulkan/commit/28e80c56e4a1606a52ddcf55392b9f007795ee9d (separate branch, to be tested).

**Comment by VoidPtr74** [comment]
`Vulkan SDK Header Version: 162

Vulkan Devices: 
- [29631] AMD 'AMD Radeon RX 6900 XT' (Discrete GPU: vulkan 1.2.159, driver AMD proprietary driver 21.1.1 - 2.0.168)

Setting Device [29631]:
- loading '../assets/textures/white.png'... (1 x 1 x 3) 6.39e-05s
- built acceleration structures in 0.629217s

Swap Chain: 
- image count: 2
- present mode: 0


Benchmark: Start scene #1 'Ray Tracing In One Weekend'
Benchmark: 52.7989 fps
Benchmark: 53.0911 fps
Benchmark: 53.0649 fps
Benchmark: 52.9763 fps
Benchmark: 53.0313 fps
Benchmark: 52.9878 fps
Benchmark: 52.9134 fps
Benchmark: 52.9528 fps
Benchmark: 52.9641 fps
Benchmark: 52.9292 fps
Benchmark: 52.8506 fps

- loading '../assets/textures/2k_mars.jpg'... (2048 x 1024 x 3) 0.0158272s
- loading '../assets/textures/2k_moon.jpg'... (2048 x 1024 x 3) 0.0174755s
- loading '../assets/textures/land_ocean_ice_cloud_2048.png'... (2048 x 1024 x 3) 0.0357427s
- built acceleration structures in 0.0657936s

Benchmark: Start scene #2 'Planets In One Weekend'
Benchmark: 51.5659 fps
Benchmark: 52.1857 fps
Benchmark: 52.2265 fps
Benchmark: 52.2721 fps
Benchmark: 52.1768 fps
Benchmark: 52.182 fps
Benchmark: 52.1622 fps
Benchmark: 52.158 fps
Benchmark: 52.1703 fps
Benchmark: 52.1909 fps
Benchmark: 52.1475 fps

- loading '../assets/models/lucy.obj'... (673335 vertices, 224491 unique vertices, 1 materials) 0.480625s
- loading '../assets/textures/white.png'... (1 x 1 x 3) 0.0001269s
- built acceleration structures in 0.201924s

Benchmark: Start scene #3 'Lucy In One Weekend'
Benchmark: 23.0563 fps
Benchmark: 24.0913 fps
Benchmark: 24.0811 fps
Benchmark: 24.1071 fps
Benchmark: 24.0666 fps
Benchmark: 24.0445 fps
Benchmark: 24.0607 fps
Benchmark: 24.042 fps
Benchmark: 24.0426 fps
Benchmark: 24.0549 fps
Benchmark: 24.0291 fps

- loading '../assets/textures/white.png'... (1 x 1 x 3) 6.37e-05s
- built acceleration structures in 0.0032901s

Benchmark: Start scene #4 'Cornell Box'
Benchmark: 40.6415 fps
Benchmark: 40.9021 fps
Benchmark: 40.9362 fps
Benchmark: 40.9647 fps
Benchmark: 40.9928 fps
Benchmark: 40.9824 fps
Benchmark: 40.9944 fps
Benchmark: 40.9894 fps
Benchmark: 40.9798 fps
Benchmark: 41.037 fps
Benchmark: 41.0263 fps

- loading '../assets/models/lucy.obj'... (673335 vertices, 224491 unique vertices, 1 materials) 0.476638s
- loading '../assets/textures/white.png'... (1 x 1 x 3) 0.0001039s
- built acceleration structures in 0.0496326s

Benchmark: Start scene #5 'Cornell Box & Lucy'
Benchmark: 14.6426 fps
Benchmark: 15.0681 fps
Benchmark: 14.9271 fps
Benchmark: 14.4557 fps
Benchmark: 14.2394 fps
Benchmark: 14.1323 fps
Benchmark: 14.0954 fps
Benchmark: 14.1053 fps
Benchmark: 14.1366 fps
Benchmark: 14.0697 fps
Benchmark: 14.082 fps

`

**Comment by GPSnoopy** [comment]
Confirmed as closed by PR #25.
