### ISSUE TITLE
Didn't work on RTX 3080 and driver 461.40 (Windows 20H2)

### ISSUE THREAD

**Issue by Keikunbr** [GPSnoopy/RayTracingInVulkan#26]
Hello.
I tried to use this application and it finished with this error message after third benchmark:

F:\Fabiano\Downloads\Compressed\RayTracingInVulkan.r6\bin>RayTracer.exe --benchmark --width 2560 --height 1440 --fullscreen --scene 1 --next-scenes --present-mode 0
Vulkan SDK Header Version: 162

Vulkan Devices:
- [8710] NVIDIA 'GeForce RTX 3080' (Discrete GPU: vulkan 1.2.155, driver NVIDIA 461.40 - 461.40.0)

Setting Device [8710]:
- loading '../assets/textures/white.png'... (1 x 1 x 3) 0.0001756s
- built acceleration structures in 0.0121975s

Swap Chain:
- image count: 2
- present mode: 0

Benchmark: Start scene #1 'Ray Tracing In One Weekend'
Benchmark: 33.2256 fps
Benchmark: 33.2382 fps
Benchmark: 33.4103 fps
Benchmark: 33.6559 fps
Benchmark: 33.6253 fps
Benchmark: 33.6682 fps
Benchmark: 33.599 fps
Benchmark: 33.6263 fps
Benchmark: 33.5912 fps
Benchmark: 33.6179 fps
Benchmark: 33.6377 fps

- loading '../assets/textures/2k_mars.jpg'... (2048 x 1024 x 3) 0.0217313s
- loading '../assets/textures/2k_moon.jpg'... (2048 x 1024 x 3) 0.0260922s
- loading '../assets/textures/land_ocean_ice_cloud_2048.png'... (2048 x 1024 x 3) 0.0508782s
- built acceleration structures in 0.0060612s

Benchmark: Start scene #2 'Planets In One Weekend'
Benchmark: 34.1146 fps
Benchmark: 34.4023 fps
Benchmark: 34.452 fps
Benchmark: 34.7287 fps
Benchmark: 34.7495 fps
Benchmark: 34.6925 fps
Benchmark: 34.7214 fps
Benchmark: 34.7081 fps
Benchmark: 34.7529 fps
Benchmark: 34.6944 fps
Benchmark: 34.7123 fps

- loading '../assets/models/lucy.obj'... (673335 vertices, 224491 unique vertices, 1 materials) 0.9469s
- loading '../assets/textures/white.png'... (1 x 1 x 3) 0.0002194s
- built acceleration structures in 0.0131662s

Benchmark: Start scene #3 'Lucy In One Weekend'
Benchmark: 31.8791 fps
Benchmark: 32.3293 fps
Benchmark: 32.3589 fps
Benchmark: 32.3509 fps
Benchmark: 32.2871 fps
Benchmark: 32.298 fps
Benchmark: 32.3041 fps
Benchmark: 32.3221 fps
Benchmark: 32.3612 fps
Benchmark: 32.3561 fps
FATAL: failed to submit draw command buffer (ERROR_DEVICE_LOST)

 0# 0x00007FF6BFDC6C32 in RayTracer
 1# 0x00007FF6BFDB559E in RayTracer
 2# 0x00007FF6BFDF18A9 in RayTracer
 3# 0x00007FF6BFE0F441 in RayTracer
 4# 0x00007FF6BFDF25E5 in RayTracer
 5# 0x00007FF6BFE0FB1F in RayTracer
 6# 0x00007FF6BFDF9183 in RayTracer
 7# 0x00007FF6BFF30404 in RayTracer
 8# BaseThreadInitThunk in KERNEL32
 9# RtlUserThreadStart in ntdll

F:\Fabiano\Downloads\Compressed\RayTracingInVulkan.r6\bin>

**Comment by GPSnoopy** [comment]
Sounds like a driver/card crash. Is it reproducible?

**Comment by Gert-dev** [comment]
I'm experiencing a crash as well, and wanted to ask if there is something special that the two Lucy examples do that the others don't.

(I'm asking because I'm experiencing crashes in other locations using ray-tracing on both Windows and Linux, but all of the demos here except the Lucy ones do work.)

**Comment by GPSnoopy** [comment]
The lucy scenes and the cornell box contains triangle geometry. These will exercise and stress a different ray tracing path compared to the first two scenes (which are based on pure procedural geometry).

`ERROR_DEVICE_LOST` tends to be serious programming bug (like a segfault). But given that in this case the app works for most people with similar hardware, I would say it's more likely faulty (or overclocked) hardware or software install.
