### ISSUE TITLE
Visualising Acceleration Structure

### ISSUE THREAD

**Issue by PMunkes** [GPSnoopy/RayTracingInVulkan#27]
Hi, I don't know if this would be difficult, but would it be possible to visualize the aabb boundaries?
I saw this very interesting visualization and wondered if it would be difficult to implement something similar:

[https://twitter.com/PierreTerdiman/status/1355851691762061312?s=20](https://twitter.com/PierreTerdiman/status/1355851691762061312?s=20)

**Comment by GPSnoopy** [comment]
By nature of the Vulkan `VK_KHR_acceleration_structure` extension, the actual implementation of the acceleration structure is left undefined. So it doesn't expose back the AABB boundaries and hierarchy in such a way that they can be visualised within the app (at least none that I know of).

Nsight Graphics allows you to visual the structures and geometry when debugging Vulkan application. I used it several times when creating this app and porting it to the newer extension. Particularly useful to debug off-by-one and other offset errors. But then again, it shows you the hierarchy and geometry that the application submitted, not the lower-level BVH of how the GPU broke down the AABB sections.

https://developer.nvidia.com/nsight-graphics

**Comment by PMunkes** [comment]
Thanks for the heads up and the explanation. Those internal tools would be very interesting, but more as a curiosity.

It seems as if it would be feasible to reverse engineer something for AMD, since they seem to implement a BVH4 structure, I found a thread where some guys are reverse engineering RDNA2 RT, in case you want more information: https://forum.beyond3d.com/threads/rdna-2-ray-tracing.62161/

I'll close this issue. Thanks again
