### ISSUE TITLE
Add a denoiser

### ISSUE THREAD

**Issue by the-spyke** [GPSnoopy/RayTracingInVulkan#30]
Please add some kind of a denoiser with at least on/off toggle support.

This way we could estimate RDNA2 ray tracing performance impact for procedural geometry scenes where denoiser should consume some of the compute units while Turing/Ampere could rely more on tensor cores.

Thank you!

**Comment by GPSnoopy** [comment]
@GoncaloFDS has a nice fork / original content using OptiX to denoise the final image: https://github.com/GoncaloFDS/Lift

I don't think OptiX AI denoiser would work on RDNA2 though, so wouldn't be an apple-to-apple comparison. Either way, I'd like to keep this project relatively close to the books "Ray Tracing In One Weekend" and thus specifically chose not to include OptiX denoising. A good denoiser requires extra images outputs such as normals and base-colours, so it's not just adding a function call.

Performance wise, the denoising is an extra steps after the raw ray tracing pass. It won't fundamentally change the performance of the ray tracing pass, just add extra time afterwards to denoise the image.

**Comment by the-spyke** [comment]
@GPSnoopy I was thinking about some cross-platform SVGF. The point is that how relevant are performance numbers without a denoiser, because you can't release a game without it. So, even if you're 10 times more powerful, but denoiser makes you 10 times slower, then you're equal at max.

P.S. I was pitching your project to [Digital Foundry](https://www.youtube.com/channel/UC9PBzalIcEQCsiIkq36PyUA) team, but results need to have some correlation with real games and without denoiser they haven't. Anyway, thank you for your work!

**Comment by GPSnoopy** [comment]
I would love for DF to use this application when investigating the ray tracing implementation of new GPUs. 😃 

In a way, that's what I find useful about this app when used for benchmarking. It specifically isolates the ray tracing hardware implementation, similar to what Quake 2 RTX and Minecraft RTX do. Whereas all other games are using hybrid approaches of standard rasterization + some ray tracing effects.

You can use Quake 2 RTX to get an idea of the impact of the denoiser on performance. IIRC it can be easily enabled/disabled. The caveat being that it's up to the game/application to decide how complex its denoiser implementation should be (and therefore its impact on performance).

**Comment by yuxiao-ash** [comment]
> 
@GPSnoopy Hi, you said that '_It specifically isolates the ray tracing hardware implementation_' , does this mean that the test performance of this project on the RTX GPU does not use the RT Core to accelerate? And while on AMD GPU, RDNA2's CU is used to accelerate ray tracing.  
Sorry I'm very new to ray tracing, I just wonder if the actual performance of this project can be faster on AMD and RTX? 
Thank you very much if you can answer my questions when you have time.

**Comment by GPSnoopy** [comment]
@yuxiao-ash It does use RT Cores whenever available. The code uses the official Vulkan `VK_KHR_ray_tracing_pipeline` extensions, which in practice uses hardware RT acceleration whenever available (that includes RTX and RDNA2).

AFAIK the only GPUs where this extension is widely available but emulated using regular compute shader is the NVIDIA 1000 series (like the GTX 1080).

You can browse the full list of GPUs that support `VK_KHR_ray_tracing_pipeline` at: https://vulkan.gpuinfo.org/listdevicescoverage.php?extension=VK_KHR_ray_tracing_pipeline&platform=all

**Comment by yuxiao-ash** [comment]
> 

OK, thank you very much！
