### ISSUE TITLE
Light?

### ISSUE THREAD

**Issue by dmarian** [GPSnoopy/RayTracingInVulkan#5]
Hello there,
  How do you handle the global light? In Graphics.frag I see you have a fixed vector but I cannot find something similar in the path tracing code. Thanks.

**Comment by GPSnoopy** [comment]
Hey. In the ray traced scenes, there is either no global ambient light or there is a sky-like ambient light. 

The distinction happens in the shaders when a ray doesn't hit anything. 
See https://github.com/GPSnoopy/RayTracingInVulkan/blob/master/assets/shaders/RayTracing.rmiss

For the scenes without a sky, i.e. the Cornell Box ones, only the local square light at the top of the box provides any lighting. It does require that a ray eventually bounces and hit this light, which usually doesn't happen. Hence why these scenes are so noisy and require a lot of samples.
