### ISSUE TITLE
Build Problem

### ISSUE THREAD

**Issue by kyamant** [GPSnoopy/RayTracingInVulkan#50]
Followed the prescribed build method for Windows:
> vcpkg_windows.bat
> build_windows.bat
No .sln file for the solution produced.
What is the correct and complete way to build this?

**Comment by GPSnoopy** [comment]
The solution file should be produced under `./build/windows/`, can you find it there?

Otherwise, did you have any error messages when running `build_windows.bat` ?

**Comment by kyamant** [comment]
Under `build`, there is only `vcpkg.windows` folder. Searched for "error" in the build output, did not find any

**Comment by GPSnoopy** [comment]
Could you provide the output of `build_windows.bat`?

Make sure you run this script within Visual Studio x64 Tools command line. Otherwise it won't work

**Comment by kyamant** [comment]
I was using `Developer Command Prompt for VS 2019`, rebuilding with `x64 Native Tools Command Prompt` seems to fix it.
