### ISSUE TITLE
Failed to load icon

### ISSUE THREAD

**Issue by Melechtna** [GPSnoopy/RayTracingInVulkan#55]
I'm trying to get this working in Linux to test out AMDs (admittedly borked) ray tracing. Every time I do, I get this output.

FATAL: failed to load icon

 0# 0x0000557A586C76BE in /opt/raytracinginvulkan/bin/RayTracer
 1# 0x0000557A586C95D8 in /opt/raytracinginvulkan/bin/RayTracer
 2# 0x0000557A586FE91E in /opt/raytracinginvulkan/bin/RayTracer
 3# 0x0000557A587105E1 in /opt/raytracinginvulkan/bin/RayTracer
 4# 0x0000557A58721FC1 in /opt/raytracinginvulkan/bin/RayTracer
 5# 0x0000557A586CC63E in /opt/raytracinginvulkan/bin/RayTracer
 6# 0x00007FCC38A75310 in /usr/lib/libc.so.6
 7# __libc_start_main in /usr/lib/libc.so.6
 8# 0x0000557A586CD555 in /opt/raytracinginvulkan/bin/RayTracer

Is this something to do with that borked implementation, or is this something else?

**Comment by GPSnoopy** [comment]
Hi @Melechtna,

Make sure you run the executable from the `bin` directory (i.e. as a working directory), otherwise it won't find its assets. I have to admit I haven't put in any logic to automatically deduce the executable directory.

**Comment by Melechtna** [comment]
> Hi @Melechtna,
> 
> Make sure you run the executable from the `bin` directory (i.e. as a working directory), otherwise it won't find its assets. I have to admit I haven't put in any logic to automatically deduce the executable directory.

Yep, that was the issue, now I just need to figure out the pipeline issue, which is unrelated. Thanks!

**Comment by ric96** [comment]
Hi, I have an A380 on Linux and its still failing to run
```
$ ./RayTracer --scene 1
Vulkan SDK Header Version: 243

Vulkan Instance Extensions: 
- VK_KHR_device_group_creation (0.0.1)
- VK_KHR_display (0.0.23)
- VK_KHR_external_fence_capabilities (0.0.1)
- VK_KHR_external_memory_capabilities (0.0.1)
- VK_KHR_external_semaphore_capabilities (0.0.1)
- VK_KHR_get_display_properties2 (0.0.1)
- VK_KHR_get_physical_device_properties2 (0.0.2)
- VK_KHR_get_surface_capabilities2 (0.0.1)
- VK_KHR_surface (0.0.25)
- VK_KHR_surface_protected_capabilities (0.0.1)
- VK_KHR_wayland_surface (0.0.6)
- VK_KHR_xcb_surface (0.0.6)
- VK_KHR_xlib_surface (0.0.6)
- VK_EXT_acquire_drm_display (0.0.1)
- VK_EXT_acquire_xlib_display (0.0.1)
- VK_EXT_debug_report (0.0.10)
- VK_EXT_debug_utils (0.0.2)
- VK_EXT_direct_mode_display (0.0.1)
- VK_EXT_display_surface_counter (0.0.1)
- VK_EXT_swapchain_colorspace (0.0.4)
- VK_EXT_surface_maintenance1 (0.0.1)
- VK_KHR_portability_enumeration (0.0.1)
- VK_LUNARG_direct_driver_loading (0.0.1)

Vulkan Instance Layers: 
- VK_LAYER_VALVE_steam_overlay_32 (1.3.207) : Steam Overlay Layer
- VK_LAYER_VALVE_steam_overlay_64 (1.3.207) : Steam Overlay Layer
- VK_LAYER_VALVE_steam_fossilize_32 (1.3.207) : Steam Pipeline Caching Layer
- VK_LAYER_VALVE_steam_fossilize_64 (1.3.207) : Steam Pipeline Caching Layer
- VK_LAYER_MESA_device_select (1.3.211) : Linux device selection layer
- VK_LAYER_FROG_gamescope_wsi (1.3.221) : Gamescope WSI (XWayland Bypass) Layer (x86_64)
- VK_LAYER_KHRONOS_validation (1.3.243) : Khronos Validation Layer

Vulkan Devices: 
- [22181] INTEL 'Intel(R) Arc(tm) A380 Graphics (DG2)' (Discrete GPU: vulkan 1.3.246, driver Intel open-source Mesa driver Mesa 23.1.5 - 23.1.5)
- [0] UnknownVendor 'llvmpipe (LLVM 16.0.6, 256 bits)' (CPU: vulkan 1.3.246, driver llvmpipe Mesa 23.1.5 (LLVM 16.0.6) - 0.0.1)

Setting Device [22181]:
FATAL: found no matching compute queue

 0# 0x000000000040D1BF in ./RayTracer
 1# 0x000000000040E32E in ./RayTracer
 2# 0x000000000045338C in ./RayTracer
 3# 0x000000000044A1E2 in ./RayTracer
 4# 0x000000000045FF16 in ./RayTracer
 5# 0x00000000004726A4 in ./RayTracer
 6# 0x000000000044B2EA in ./RayTracer
 7# 0x0000000000417C1D in ./RayTracer
 8# 0x00007F1A00E49B4A in /lib64/libc.so.6
 9# __libc_start_main in /lib64/libc.so.6
10# 0x00000000004186F5 in ./RayTracer

```
