### ISSUE TITLE
Option to select GPU

### ISSUE THREAD

**Issue by Mart-Bogdan** [GPSnoopy/RayTracingInVulkan#66]
Currently when I run it I recieve following output:

```
Vulkan Devices: 
- [9373] NVIDIA 'NVIDIA GeForce RTX 3070 Laptop GPU' (Discrete GPU: vulkan 1.3.236, driver NVIDIA 530.41.03 - 530.41.12)
- [5688] AMD 'AMD Radeon Graphics (RADV RENOIR)' (Integrated GPU: vulkan 1.3.238, driver radv Mesa 23.0.1 - 23.0.1)

Setting Device [9373]:
```

Is there way to select device? 
Running with `--help` option don't show this as option

**Comment by GPSnoopy** [comment]
@Mart-Bogdan I've added the `--visible-device` command line option. So you can use as `--visible-device=5688` or ` --visible-device 5688` if you want only your AMD device to be visible to the application.

Note that you can specify the option multiple times if you want multiple devices to be visible.
