### ISSUE TITLE
VK_BUFFER_USAGE_VERTEX_BUFFER_BIT and VK_BUFFER_USAGE_INDEX_BUFFER_BIT

### ISSUE THREAD

**Issue by kyamant** [GPSnoopy/RayTracingInVulkan#74]
Vertex and Index buffers are created with the usage types mentioned in the title.
However, these are in fact storage buffers used by shaders of the RayTracing pipeline.
The _VK_BUFFER_USAGE_VERTEX_BUFFER_BIT_ and _VK_BUFFER_USAGE_INDEX_BUFFER_BIT_ usage specs are related to the graphics pipeline (vertex shader).
Could you please elaborate on your choice of these usage specs in a ray tracing pipeline?

**Comment by GPSnoopy** [comment]
IIRC the assets are shared with the non-raytracing pipeline (when you disable the raytracing option).

**Comment by kyamant** [comment]
These types of buffers are specific to vertex shaders; what benefits do they present to raytracing shaders?

**Comment by GPSnoopy** [comment]
These buffers are used by both the ray tracing acceleration structures and the non-raytracing pipeline (on the left side of the windows, there is an option to disable ray tracing and fall back to the regular rasterized pipeline).

If the option did not exist, then these flags would not be needed as you pointed.

**Comment by kyamant** [comment]
Thanks for the clarification.
