### ISSUE TITLE
validation-error: acceleration-structure-buffer is missing 'VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT'

### ISSUE THREAD

**Issue by fabian-lunarg** [GPSnoopy/RayTracingInVulkan#78]
running the application with validation-layers enabled I'm seeing the following error:

`VUID-vkGetAccelerationStructureDeviceAddressKHR-pInfo-09542(ERROR / SPEC): msgNum: -457819186 - Validation Error: [ VUID-vkGetAccelerationStructureDeviceAddressKHR-pInfo-09542 ] | MessageID = 0xe4b63bce | vkGetAccelerationStructureDeviceAddressKHR(): pInfo->accelerationStructure.buffer was created with usage flag(s) VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_STORAGE_BIT_KHR. The Vulkan spec states: The buffer on which pInfo->accelerationStructure was placed must have been created with the VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT usage flag (https://vulkan.lunarg.com/doc/view/1.3.280.0/linux/1.3-extensions/vkspec.html#VUID-vkGetAccelerationStructureDeviceAddressKHR-pInfo-09542)`

using: ubuntu 22.04, nvidia 550.67, vulkan SDK 1.3.280.1

**Comment by GPSnoopy** [comment]
This has been fixed. The CI/CD is currently broken, but this is a separate issue (CMake regression, fixed in 3.29.2).
