### ISSUE TITLE
Idea to improve camera controls

### ISSUE THREAD

**Issue by misner5** [GPSnoopy/RayTracingInVulkan#9]
I've been experimenting with this project... I think it's great!  
Really nice code and organization of Vulkan and 3D concepts.
One thing I noticed is the camera navigation is much nicer if you reverse the up vector order.

In RayTracer::GetUniformBufferObject, I changed the code to:
```
const auto model =
	glm::rotate(glm::mat4(1.0f), cameraRotX * glm::radians(90.0f), glm::vec3(1.0f, 0.0f, 0.0f)) *
	glm::rotate(glm::mat4(1.0f), cameraRotY * glm::radians(90.0f), glm::vec3(0.0f, 1.0f, 0.0f));
```
I tried to get it more like a camera in a 3D app... feels a bit easier to navigate.

**Comment by GPSnoopy** [comment]
Hi @misner5,

I can't really say I favour one way over the other. I think we can both agree the current controls are pretty limited, although with the added bonus of being very simple.

I think if I were to revisit this area, I would probably want to investigate controls closer to what a video game would do (WASD, SHIFT/CONTROL and mouse look). Hopefully in a way that works no matter whether you use a QWERTY or an AZERTY layount.

This would allow to navigate the scenes in more interesting ways.

**Comment by misner5** [comment]
Yah that makes sense... I really like the simplicity of the code / user experience... it's cool your designing with simplicity as an overall goal.

Also I come from a art / engineering tool background so the controls are different than a game perspective... A further change I made in this code was having the mouse wheel zoom in and out (moving FoV slider).  Just made it great as a mini-3D prototyping environment, like a Vulkan viewer.  It's awesome to have a testing environment like this that does a ton in a small amount of code: fast to compile, easy to prototype changes, ect.

Anyways awesome job I really like this project.

**Comment by GPSnoopy** [comment]
I'm adding better camera controls with PR #10. 

It keeps the old style controls when pressing the right-mouse button. Pressing left-mouse button controls the camera in a free-look style (aka FPS game style). WASD and SHIFT/CTRL keys (or equivalent positions in AZERTY) control the camera translation.
